version: "3"
services:
  nginx:
    # restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "5000:5000"
    links:
      - web1:web1
      - web2:web2
      - web3:web3
      - api:api   

  web1:
    # restart: always
    build: ./web
    # env_file: .env
    expose:
      - "8000"
    links:
      # - postgres:postgres
      - redis:redis


  web2:
    # restart: always
    build: ./web
    # env_file: .env
    expose:
      - "8000"
    links:
      # - postgres:postgres
      - redis:redis

  web3:
    # restart: always
    build: ./web
    # env_file: .env
    expose:
      - "8000"
    links:
      # - postgres:postgres
      - redis:redis

  api:
    # restart: always
    build: ./api
    expose:
      - "5000"

  # postgresql:
  #   build: ./postgres
  #   volumes:
  #     - ./pgdata:/var/lib/nestor/postgresql/data/pgdata
  #   ports:
  #     - "5433:5432"

  redis:
    restart: always
    image: redis:latest
